version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00000000
      POSTGRES_DB: ecommerce_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: "5000"
      DATABASE_URL: "postgresql://postgres:00000000@postgres:5432/ecommerce_db"
      JWT_SECRET: "your-super-secret-jwt-key"
      JWT_REFRESH_SECRET: "your-super-secret-refresh-key"
      JWT_EXPIRES_IN: "15m"
      CLOUDINARY_CLOUD_NAME: "kznj0kgt"
      CLOUDINARY_API_KEY: "269753217238713"
      CLOUDINARY_API_SECRET: "cdQzyEuqp-Zq2SvjNPvBMDMbQkE"
      FRONTEND_URL: "http://localhost:5173"
      ALLOWED_ORIGINS: "http://localhost:5173,http://172.26.32.1:5175"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    restart: always
    ports:
      - "5175:80"
    depends_on:
      - backend

volumes:
  postgres_data:
